apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: nodejs-pipelinerun-tekton-1.0
spec:
  serviceAccountName: docker-login
  pipelineRef:
    name: nodejs-pipeline
  params:
    - name: IMAGE
      value: docker.io/mkhilnan/nodejs-k8-tekton
    - name: TAG
      value: v1.0
  workspaces:
    - name: linked-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 500Mi

